### PR TITLE
Added an implementation for addBatch and executeBatch

### PR DESCRIPTION
**Pull request by mehmetgunturkun**

### CODE REVIEW

**Comment by mehmetgunturkun** [comment]
@callicles I might need some help for releasing and publishing this build into our artifactory

**Comment by mehmetgunturkun** [comment]
Alternatives:
1. Through our deployment process:
    1. Have a build in Circle CI
    2. Create a repo on JFrog
    3. Update circle.yaml to deploy release

2. Quick way
    1. I can merge and deploy to JFrog Artifactory manually

**Comment by callicles** [comment]
We could do 2 provided we intend to PR against the mainline

**Comment by mehmetgunturkun** [comment]
Yeah, it's just emulating. I tried to concatenate the SQLs into one and run at once but it took the same amount of time.

Here is the issue for `executeBatch`: https://issues.apache.org/jira/browse/HIVE-16221?jql=project%20%3D%20HIVE%20AND%20text%20~%20%22batch%20insert%22

But it does not have that much detail or discussion

**Comment by callicles** [comment]
You should start commenting on it and describe what you did. It will ping the opener and we will see what they say.

**Pull request merged**
